spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/about_error?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379

jwt:
  secretKey: swhefoahewoahfnioIOOh2141292q9rh923rhh29f3h92hn3r99

logging:
  level:
    com.tutorial: debug
